services:
  foruscorp.trucks.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5003
    ports:
      - "5003"

  foruscorp.fuelstations.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5002
      # - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "5002"
    # volumes:
    #   - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    #   - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #   - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    #   - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  foruscorp.truckstracking.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5001
      # - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "5001"
    # volumes:
    #   - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    #   - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #   - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    #   - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  foruscorp.fuelroutes.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5004
      # - ASPNETCORE_HTTPS_PORTS=5004
    ports:
      - "5004"
      # - "5004"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  foruscorp.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5011
    ports:
      - "5000"
      - "5011"
    # volumes:
    #   - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    #   - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #   - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    #   - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  # foruscorp.fuelroutes.auth:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=5007
  #   ports:
  #     - "5007"


  foruscorp.auth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=5007
      # - ASPNETCORE_HTTPS_PORTS=5008
    ports:
      - "5007"
      # - "5008" 
    # volumes:
    #   - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    #   - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #   - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    #   - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro



