services:


  foruscorp.gateway:
    container_name: foruscorp-gateway
    image: ${DOCKER_REGISTRY-}foruscorpgateway
    build:
      context: .
      dockerfile: src/Gateway/Foruscorp.Gateway/Dockerfile
    volumes:
      # - ./appsettings.json:/etc/yarp.config
      - ./certs/certificate.pfx:/etc/certs/certificate.pfx
    ports:
      - "5000:5000" 
      - "5011:5011" 
    environment:
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5011
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp-gateway-prod-us-west-0.grafana.net/otlp # OpenTelemetry endpoint for metrics and traces
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_HEADERS=Authorization=Basic MTMwNDg5ODpnbGNfZXlKdklqb2lNVFEzTWpVd01DSXNJbTRpT2lKemRHRmpheTB4TXpBME9EazRMVzkwYkhBdGQzSnBkR1V0WjNKaFptRnVZUzAwZFhOamIzSndJaXdpYXlJNklqYzFOalJoZUZGTGJUSkNNbFF3TlZVMmMzbG1WbGhITkNJc0ltMGlPbnNpY2lJNkluQnliMlF0ZFhNdGQyVnpkQzB3SW4xOQ==
    networks:
      - foruscorp-docker-network


    
  foruscorp.auth:
    container_name: foruscorp-auth
    image: ${DOCKER_REGISTRY-}foruscorpauth
    build:
      context: .
      dockerfile: src/Auth/Foruscorp.Auth/Dockerfile
    ports:
      - 5007:5007
    environment:
      - MessageBroker__HostName=rabbitmq://rabbitmq
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
      - ConnectionStrings__DefaultConnection=Host=foruscorp.db;Port=5432;Database=ForuscorpDB;Username=postgres;Password=your_secure_password
      - ASPNETCORE_HTTP_PORTS=5007
      - DOTNET_ENVIRONMENT=Development
    networks:
      - foruscorp-docker-network



  foruscorp.truckstracking.api:
    container_name: truckstracking-api
    image: ${DOCKER_REGISTRY-}foruscorptruckstrackingapi
    build:
      context: .
      dockerfile: src/TrucksTracking/Foruscorp.TrucksTracking.API/Dockerfile
    ports:
      - 5001:5001
    environment:
      - ConnectionStrings__DefaultConnection=Host=foruscorp.db;Port=5432;Database=ForuscorpDB;Username=postgres;Password=your_secure_password
      - ASPNETCORE_ENVIRONMENT=Development
      - MessageBroker__HostName=rabbitmq://rabbitmq
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
      - SamsaraApi__ApiToken=${SAMSARA_API_TOKEN}
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341 # Add Seq URL for Serilog
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889 # OpenTelemetry endpoint for metrics and traces
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp-gateway-prod-us-west-0.grafana.net/otlp # OpenTelemetry endpoint for metrics and traces
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_HEADERS=Authorization=Basic MTMwNDg5ODpnbGNfZXlKdklqb2lNVFEzTWpVd01DSXNJbTRpT2lKemRHRmpheTB4TXpBME9EazRMVzkwYkhBdGQzSnBkR1V0WjNKaFptRnVZUzAwZFhOamIzSndJaXdpYXlJNklqYzFOalJoZUZGTGJUSkNNbFF3TlZVMmMzbG1WbGhITkNJc0ltMGlPbnNpY2lJNkluQnliMlF0ZFhNdGQyVnpkQzB3SW4xOQ==
    depends_on:
      - foruscorp.db
      - rabbitmq
      # - seq # Add dependency on Seq
    networks:
      - foruscorp-docker-network
    restart: unless-stopped


  foruscorp.fuelstations.api:
    container_name: fuelstations-api
    image: ${DOCKER_REGISTRY-}foruscorpfuelstationsapi
    build: 
      context: .
      dockerfile: src/FuelStations/Foruscorp.FuelStations.API/Dockerfile
    ports:
      - 5002:5002
    environment:
      - ConnectionStrings__DefaultConnection=Host=foruscorp.db;Port=5432;Database=ForuscorpDB;Username=postgres;Password=your_secure_password
      - ASPNETCORE_ENVIRONMENT=Development
      - MessageBroker__HostName=rabbitmq://rabbitmq
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp-gateway-prod-us-west-0.grafana.net/otlp # OpenTelemetry endpoint for metrics and traces
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_HEADERS=Authorization=Basic MTMwNDg5ODpnbGNfZXlKdklqb2lNVFEzTWpVd01DSXNJbTRpT2lKemRHRmpheTB4TXpBME9EazRMVzkwYkhBdGQzSnBkR1V0WjNKaFptRnVZUzAwZFhOamIzSndJaXdpYXlJNklqYzFOalJoZUZGTGJUSkNNbFF3TlZVMmMzbG1WbGhITkNJc0ltMGlPbnNpY2lJNkluQnliMlF0ZFhNdGQyVnpkQzB3SW4xOQ==
    depends_on:
      - foruscorp.db
      - rabbitmq
    networks:
      - foruscorp-docker-network

  foruscorp.trucks.api:
    container_name: trucks-api
    image: ${DOCKER_REGISTRY-}foruscorptrucksapi
    build:
      context: .
      dockerfile: src/Trucks/Foruscorp.Trucks.API/Dockerfile
    ports:
      - 5003:5003
    environment:
      - ConnectionStrings__DefaultConnection=Host=foruscorp.db;Port=5432;Database=ForuscorpDB;Username=postgres;Password=your_secure_password
      - ASPNETCORE_ENVIRONMENT=Development
      - MessageBroker__HostName=rabbitmq://rabbitmq
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
      - SamsaraApi__ApiToken=${SAMSARA_API_TOKEN}
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp-gateway-prod-us-west-0.grafana.net/otlp # OpenTelemetry endpoint for metrics and traces
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_HEADERS=Authorization=Basic MTMwNDg5ODpnbGNfZXlKdklqb2lNVFEzTWpVd01DSXNJbTRpT2lKemRHRmpheTB4TXpBME9EazRMVzkwYkhBdGQzSnBkR1V0WjNKaFptRnVZUzAwZFhOamIzSndJaXdpYXlJNklqYzFOalJoZUZGTGJUSkNNbFF3TlZVMmMzbG1WbGhITkNJc0ltMGlPbnNpY2lJNkluQnliMlF0ZFhNdGQyVnpkQzB3SW4xOQ==
    depends_on:
      - foruscorp.db
      - rabbitmq
    networks:
      - foruscorp-docker-network

  foruscorp.fuelroutes.api:
    container_name: fuelroutes-api
    image: ${DOCKER_REGISTRY-}foruscorpfuelroutesapi
    build:
        context: .
        dockerfile: src/FuelRoute/Foruscorp.FuelRoute.API/Dockerfile
    ports:
      - 5004:5004
    environment:
      - ConnectionStrings__DefaultConnection=Host=foruscorp.db;Port=5432;Database=ForuscorpDB;Username=postgres;Password=your_secure_password
      - ASPNETCORE_ENVIRONMENT=Development
      - MessageBroker__HostName=rabbitmq://rabbitmq
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp-gateway-prod-us-west-0.grafana.net/otlp # OpenTelemetry endpoint for metrics and traces
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_HEADERS=Authorization=Basic MTMwNDg5ODpnbGNfZXlKdklqb2lNVFEzTWpVd01DSXNJbTRpT2lKemRHRmpheTB4TXpBME9EazRMVzkwYkhBdGQzSnBkR1V0WjNKaFptRnVZUzAwZFhOamIzSndJaXdpYXlJNklqYzFOalJoZUZGTGJUSkNNbFF3TlZVMmMzbG1WbGhITkNJc0ltMGlPbnNpY2lJNkluQnliMlF0ZFhNdGQyVnpkQzB3SW4xOQ==
    depends_on:
      - foruscorp.db
      - rabbitmq
    networks:
      - foruscorp-docker-network


  # gateway.api:
  #   container_name: gateway-api
  #   image: mcr.microsoft.com/dotnet/nightly/yarp:latest
  #   volumes:
  #     - ./appsettings.json:/etc/yarp.config
  #     - ./certs/server.pfx:/etc/certs/certificate.pfx
  #   ports:
  #     - "5011:5011" 
  #     - "5000:5000" 
  #   networks:
  #     - foruscorp-docker-network

  foruscorp.db:
    container_name: foruscorp-postgres
    image: postgres:latest
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_secure_password
      - POSTGRES_DB=ForuscorpDB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - foruscorp-docker-network


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672 
      - 15672:15672 
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - foruscorp-docker-network


  aspire-dashboard:
    container_name: aspire-dashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    ports:
      - 18888:18888
      - 4317:4317 # OpenTelemetry gRPC port for metrics and traces
    environment:
      - DOTNET_ENVIRONMENT=Development
      - Dashboard__Otlp__EndpointUrl=http://aspire-dashboard:4317
      - Dashboard__Frontend__AuthMode=Unsecured # Set to 'BrowserToken' for secured mode
      # - Dashboard__Frontend__BrowserToken=your_secure_browser_token # Uncomment for secured 
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true # Allow anonymous access for development 
    networks:
      - foruscorp-docker-network
    depends_on:
      - foruscorp.db
      - rabbitmq
      - foruscorp.truckstracking.api
      - foruscorp.fuelstations.api
      - foruscorp.trucks.api
      - foruscorp.fuelroutes.api


  # seq:
  #   container_name: seq
  #   image: datalust/seq:latest
  #   ports:
  #     - 5341:80
  #     - 5342:5341
  #   environment:
  #     - ACCEPT_EULA=Y
  #     # - SEQ_RETENTIONDAYS=2
  #     # - SEQ_FIRSTRUN_ADMINPASSWORD=YourStr0ngP@ssw0rd
  #   volumes:
  #     - seq-data:/data
  #   networks:
  #     - foruscorp-docker-network
  #   restart: unless-stopped







networks:
  foruscorp-docker-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  rabbitmq-data:
    driver: local
  seq-data:
    driver: local




