# services:
#   foruscorp.trucks.api:
#     image: ${DOCKER_REGISTRY-}foruscorptrucksapi
#     build:
#       context: .
#       dockerfile: src/Trucks/Foruscorp.Trucks.API/Dockerfile

#   foruscorp.fuelstations.api:
#     image: ${DOCKER_REGISTRY-}foruscorpfuelstationsapi
#     build:
#       context: .
#       dockerfile: src/FuelStations/Foruscorp.FuelStations.API/Dockerfile


#   foruscorp.truckstracking.api:
#     image: ${DOCKER_REGISTRY-}foruscorptruckstrackingapi
#     build:
#       context: .
#       dockerfile: src/TrucksTracking/Foruscorp.TrucksTracking.API/Dockerfile


services:

  foruscorp.truckstracking.api:
    container_name: truckstracking-api
    image: ${DOCKER_REGISTRY-}foruscorptruckstrackingapi
    build:
      context: .
      dockerfile: src/TrucksTracking/Foruscorp.TrucksTracking.API/Dockerfile
    ports:
      - 5001:5001
    environment:
      - ConnectionStrings__DefaultConnection=Host=foruscorp.db;Port=5432;Database=ForuscorpDB;Username=postgres;Password=your_secure_password
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - foruscorp.db
    networks:
      - foruscorp-docker-network

  foruscorp.fuelstations.api:
    container_name: fuelstations-api
    image: ${DOCKER_REGISTRY-}foruscorpfuelstationsapi
    build:
      context: .
      dockerfile: src/FuelStations/Foruscorp.FuelStations.API/Dockerfile
    ports:
      - 5002:5002
    environment:
      - ConnectionStrings__DefaultConnection=Host=foruscorp.db;Port=5432;Database=ForuscorpDB;Username=postgres;Password=your_secure_password
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - foruscorp.db
    networks:
      - foruscorp-docker-network

  foruscorp.trucks.api:
    container_name: trucks-api
    image: ${DOCKER_REGISTRY-}foruscorptrucksapi
    build:
      context: .
      dockerfile: src/Trucks/Foruscorp.Trucks.API/Dockerfile
    ports:
      - 5003:5003
    environment:
      - ConnectionStrings__DefaultConnection=Host=foruscorp.db;Port=5432;Database=ForuscorpDB;Username=postgres;Password=your_secure_password
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - foruscorp.db
    networks:
      - foruscorp-docker-network


    
  gateway.api: 
    container_name: gateway-api
    image: mcr.microsoft.com/dotnet/nightly/yarp:latest
    volumes:
      - ./appsettings.json:/etc/yarp.config
    ports:
         - "5000:5000"
    networks:
        - foruscorp-docker-network


  foruscorp.db:
    container_name: foruscorp-postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_secure_password
      - POSTGRES_DB=ForuscorpDB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - foruscorp-docker-network



networks:
  foruscorp-docker-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local

