services:
  foruscorp.truckstracking.api:
    container_name: truckstracking-api
    image: ${DOCKER_REGISTRY-}foruscorptruckstrackingapi
    build:
      context: .
      dockerfile: src/TrucksTracking/Foruscorp.TrucksTracking.API/Dockerfile
    ports:
      - 5001:5001
    environment:
      - ConnectionStrings__DefaultConnection=Host=foruscorp.db;Port=5432;Database=ForuscorpDB;Username=postgres;Password=your_secure_password
      - ASPNETCORE_ENVIRONMENT=Development
      - MessageBroker__HostName=rabbitmq://rabbitmq
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
      - SamsaraApi__ApiToken=${SAMSARA_API_TOKEN}
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341 # Add Seq URL for Serilog
    depends_on:
      - foruscorp.db
      - rabbitmq
      - seq # Add dependency on Seq
    networks:
      - foruscorp-docker-network
    restart: unless-stopped


  foruscorp.fuelstations.api:
    container_name: fuelstations-api
    image: ${DOCKER_REGISTRY-}foruscorpfuelstationsapi
    build:
      context: .
      dockerfile: src/FuelStations/Foruscorp.FuelStations.API/Dockerfile
    ports:
      - 5002:5002
    environment:
      - ConnectionStrings__DefaultConnection=Host=foruscorp.db;Port=5432;Database=ForuscorpDB;Username=postgres;Password=your_secure_password
      - ASPNETCORE_ENVIRONMENT=Development
      - MessageBroker__HostName=rabbitmq://rabbitmq
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
    depends_on:
      - foruscorp.db
      - rabbitmq
    networks:
      - foruscorp-docker-network

  foruscorp.trucks.api:
    container_name: trucks-api
    image: ${DOCKER_REGISTRY-}foruscorptrucksapi
    build:
      context: .
      dockerfile: src/Trucks/Foruscorp.Trucks.API/Dockerfile
    ports:
      - 5003:5003
    environment:
      - ConnectionStrings__DefaultConnection=Host=foruscorp.db;Port=5432;Database=ForuscorpDB;Username=postgres;Password=your_secure_password
      - ASPNETCORE_ENVIRONMENT=Development
      - MessageBroker__HostName=rabbitmq://rabbitmq
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
      - SamsaraApi__ApiToken=${SAMSARA_API_TOKEN}
    depends_on:
      - foruscorp.db
      - rabbitmq
    networks:
      - foruscorp-docker-network

  foruscorp.fuelroutes.api:
    container_name: fuelroutes-api
    image: ${DOCKER_REGISTRY-}foruscorpfuelroutesapi
    build:
        context: .
        dockerfile: src/FuelRoute/Foruscorp.FuelRoute.API/Dockerfile
    ports:
      - 5004:5004
    environment:
      - ConnectionStrings__DefaultConnection=Host=foruscorp.db;Port=5432;Database=ForuscorpDB;Username=postgres;Password=your_secure_password
      - ASPNETCORE_ENVIRONMENT=Development
      - MessageBroker__HostName=rabbitmq://rabbitmq
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
    depends_on:
      - foruscorp.db
      - rabbitmq
    networks:
      - foruscorp-docker-network


  gateway.api:
    container_name: gateway-api
    image: mcr.microsoft.com/dotnet/nightly/yarp:latest
    volumes:
      - ./appsettings.json:/etc/yarp.config
      - ./certs/certificate.pfx:/etc/certs/certificate.pfx
    ports:
      - "5011:5011" 
      - "5000:5000" 
    networks:
      - foruscorp-docker-network

  foruscorp.db:
    container_name: foruscorp-postgres
    image: postgres:latest
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_secure_password
      - POSTGRES_DB=ForuscorpDB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - foruscorp-docker-network


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672 
      - 15672:15672 
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - foruscorp-docker-network


  aspire-dashboard:
    container_name: aspire-dashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.0
    ports:
      - 18888:18888
      - 4317:4317 # OpenTelemetry gRPC port for metrics and traces
    environment:
      - DOTNET_ENVIRONMENT=Development
      - Dashboard__Otlp__EndpointUrl=http://aspire-dashboard:4317
      - Dashboard__Frontend__AuthMode=Unsecured # Set to 'BrowserToken' for secured mode
      # - Dashboard__Frontend__BrowserToken=your_secure_browser_token # Uncomment for secured mode
    networks:
      - foruscorp-docker-network
    depends_on:
      - foruscorp.db
      - rabbitmq
      - foruscorp.truckstracking.api
      - foruscorp.fuelstations.api
      - foruscorp.trucks.api
      - foruscorp.fuelroutes.api


  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
      - 5341:80
      - 5342:5341
    environment:
      - ACCEPT_EULA=Y
      - SEQ_RETENTIONDAYS=2
    volumes:
      - seq-data:/data
    networks:
      - foruscorp-docker-network
    restart: unless-stopped


networks:
  foruscorp-docker-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  rabbitmq-data:
    driver: local
  seq-data:
    driver: local
