
# version: '3.8'

# services:


#   foruscorp.truckstracking.api:
#     image: ${DOCKER_REGISTRY-}foruscorptruckstrackingapi
#     build:
#       context: .
#       dockerfile: src/TrucksTracking/Foruscorp.TrucksTracking.API/Dockerfile
#     ports:
#       - 5001:5001
#     environment:
#       - ConnectionStrings__DefaultConnection=Host=foruscorp.db;Port=5432;Database=ForuscorpDB;Username=postgres;Password=your_secure_password
#       - ASPNETCORE_ENVIRONMENT=Development
#     depends_on:
#       - foruscorp.db
#     networks:
#       - foruscorp-docker-network

      
#   foruscorp.fuelstations.api:
#     image: ${DOCKER_REGISTRY-}foruscorpfuelstationsapi
#     build:
#       context: .
#       dockerfile: src/FuelStations/Foruscorp.FuelStations.API/Dockerfile
#     ports:
#       - 5002:5002
#     environment:
#       - ConnectionStrings__DefaultConnection=Host=foruscorp.db;Port=5432;Database=ForuscorpDB;Username=postgres;Password=your_secure_password
#       - ASPNETCORE_ENVIRONMENT=Development
#     depends_on:
#       - foruscorp.db
#     networks:
#       - foruscorp-docker-network


#   foruscorp.db:
#     image: postgres:latest
#     ports:
#       - 5432:5432
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=your_secure_password
#       - POSTGRES_DB=ForuscorpDB
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     networks:
#       - foruscorp-docker-network


# networks:
#   foruscorp-docker-network:
#     driver: bridge

# volumes:
#   postgres-data:
#     driver: local
    


version: '3.8'

services:
  foruscorp.truckstracking.api:
    container_name: truckstracking-api
    image: ${DOCKER_REGISTRY-}foruscorptruckstrackingapi
    build:
      context: .
      dockerfile: src/TrucksTracking/Foruscorp.TrucksTracking.API/Dockerfile
    ports:
      - 5001:5001
    environment:
      - ConnectionStrings__DefaultConnection=Host=foruscorp.db;Port=5432;Database=ForuscorpDB;Username=postgres;Password=your_secure_password
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - foruscorp.db
    networks:
      - foruscorp-docker-network

  foruscorp.fuelstations.api:
    container_name: fuelstations-api
    image: ${DOCKER_REGISTRY-}foruscorpfuelstationsapi
    build:
      context: .
      dockerfile: src/FuelStations/Foruscorp.FuelStations.API/Dockerfile
    ports:
      - 5002:5002
    environment:
      - ConnectionStrings__DefaultConnection=Host=foruscorp.db;Port=5432;Database=ForuscorpDB;Username=postgres;Password=your_secure_password
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - foruscorp.db
    networks:
      - foruscorp-docker-network

  foruscorp.db:
    container_name: foruscorp-postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_secure_password
      - POSTGRES_DB=ForuscorpDB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - foruscorp-docker-network

networks:
  foruscorp-docker-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local