name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies 📂
      run: dotnet restore ./Foruscorp.sln
      
    - name: Build 🧱
      run: dotnet build ./Foruscorp.sln --no-restore

    # - name: Test 🧪
    # run: dotnet test ./I3Lab.sln --no-build --verbosity normal

  # Test:
  #   runs-on: ubuntu-latest
  #   needs: Build

  #   steps:
  #   - uses: actions/checkout@v4

  #   - name: Setup .NET
  #     uses: actions/setup-dotnet@v4
  #     with:
  #       dotnet-version: 8.0.x

  #   - name: Restore dependencies
  #     run: dotnet restore ./Foruscorp.sln

  #   - name: Test
  #     run: dotnet test ./Foruscorp.sln --no-build --verbosity normal

  # Deploy:
  #   runs-on: ubuntu-latest
  #   needs: Test

  #   steps:
  #   - name: Install SSH client
  #     run: sudo apt-get install openssh-client

  #   - name: Add SSH key
  #     uses: webfactory/ssh-agent@v0.8.1
  #     with:
  #       ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

  #   - name: Deploy code via Git
  #     run: |
  #       git remote add production ssh://${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/repos/Foruscorp.git
  #       git push production master

  #   - name: Deploy with docker-compose
  #     run: |
  #       ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd /path/to/deploy && docker-compose pull && docker-compose up -d"

