apiVersion: apps/v1
kind: Deployment
metadata:
  name: foruscorp-fuelroutes-api
  namespace: foruscorp
  labels:
    app: foruscorp-fuelroutes-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foruscorp-fuelroutes-api
  template:
    metadata:
      labels:
        app: foruscorp-fuelroutes-api
    spec:
      containers:
      - name: fuelroutes
        image: futondoker/foruscorpfuelroutesapi:v1
        ports:
        - containerPort: 5004
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: foruscorp-config
              key: ASPNETCORE_ENVIRONMENT
        - name: MessageBroker__HostName
          valueFrom:
            configMapKeyRef:
              name: foruscorp-config
              key: MessageBroker__HostName
        - name: MessageBroker__Username
          valueFrom:
            configMapKeyRef:
              name: foruscorp-config
              key: MessageBroker__Username
        - name: MessageBroker__Password
          valueFrom:
            configMapKeyRef:
              name: foruscorp-config
              key: MessageBroker__Password
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            configMapKeyRef:
              name: foruscorp-config
              key: ConnectionStrings__DefaultConnection
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: foruscorp-config
              key: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: foruscorp-config
              key: OTEL_EXPORTER_OTLP_PROTOCOL
        - name: OTEL_EXPORTER_OTLP_HEADERS
          valueFrom:
            configMapKeyRef:
              name: foruscorp-config
              key: OTEL_EXPORTER_OTLP_HEADERS
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: foruscorp-fuelroutes-api
  namespace: foruscorp
  labels:
    app: foruscorp-fuelroutes-api
spec:
  selector:
    app: foruscorp-fuelroutes-api
  ports:
  - port: 5004
    targetPort: 5004
    protocol: TCP
  type: ClusterIP
