apiVersion: apps/v1
kind: Deployment
metadata:
  name: foruscorp-gateway
  namespace: foruscorp
  labels:
    app: foruscorp-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foruscorp-gateway
  template:
    metadata:
      labels:
        app: foruscorp-gateway
    spec:
      containers:
      - name: gateway
        image: futondoker/foruscorpgateway:v1
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: foruscorp-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ASPNETCORE_HTTP_PORTS
          value: "5000"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: foruscorp-config
              key: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: foruscorp-config
              key: OTEL_EXPORTER_OTLP_PROTOCOL
        - name: OTEL_EXPORTER_OTLP_HEADERS
          valueFrom:
            configMapKeyRef:
              name: foruscorp-config
              key: OTEL_EXPORTER_OTLP_HEADERS
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: foruscorp-gateway
  namespace: foruscorp
  labels:
    app: foruscorp-gateway
spec:
  selector:
    app: foruscorp-gateway
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  type: LoadBalancer
