apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: foruscorp-gateway-hpa
  namespace: foruscorp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: foruscorp-gateway
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: foruscorp-auth-hpa
  namespace: foruscorp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: foruscorp-auth
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: foruscorp-truckstracking-hpa
  namespace: foruscorp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: foruscorp-truckstracking-api
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
