apiVersion: apps/v1
kind: Deployment
metadata:
  name: foruscorp-postgres
  namespace: foruscorp
  labels:
    app: foruscorp-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foruscorp-postgres
  template:
    metadata:
      labels:
        app: foruscorp-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: foruscorp-secrets
              key: postgres-password
        - name: POSTGRES_DB
          value: "ForuscorpDB"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: foruscorp-postgres
  namespace: foruscorp
  labels:
    app: foruscorp-postgres
spec:
  selector:
    app: foruscorp-postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: foruscorp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""  # Use default storage class
