apiVersion: v1
kind: Secret
metadata:
  name: foruscorp-secrets
  namespace: foruscorp
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  postgres-password: eW91cl9zZWN1cmVfcGFzc3dvcmQ=  # your_secure_password
  samsara-api-token: ""  # Add your Samsara API token here
  certificate-password: Zm9ydXNjb3Jw  # foruscorp
stringData:
  # Alternative way to specify secrets in plain text (will be base64 encoded automatically)
  # postgres-password: "your_secure_password"
  # samsara-api-token: "your_samsara_token"
  # certificate-password: "foruscorp"
