// <auto-generated />
using System;
using Foruscorp.TrucksTracking.Infrastructure.Percistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Foruscorp.TrucksTracking.Infrastructure.Migrations
{
    [DbContext(typeof(TuckTrackingContext))]
    [Migration("20250819125822_Update_Trunssaction_fix")]
    partial class Update_Trunssaction_fix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("TuckTracking")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Foruscorp.TrucksTracking.Domain.FuelStationPlans.NearFuelStationPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FuelStationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsNear")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double>("NearDistance")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("RecordedOnLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TruckId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FuelStationId");

                    b.HasIndex("RecordedOnLocationId");

                    b.HasIndex("TruckId");

                    b.ToTable("NearFuelStationPlans", "TuckTracking");
                });

            modelBuilder.Entity("Foruscorp.TrucksTracking.Domain.Transactions.Fill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Driver")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Invoice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Odometer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranTime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Driver");

                    b.HasIndex("Invoice");

                    b.HasIndex("TransactionId");

                    b.HasIndex("Unit");

                    b.ToTable("Fills", "TuckTracking");
                });

            modelBuilder.Entity("Foruscorp.TrucksTracking.Domain.Transactions.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FillId")
                        .HasColumnType("uuid");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FillId");

                    b.HasIndex("Type");

                    b.ToTable("Items", "TuckTracking");
                });

            modelBuilder.Entity("Foruscorp.TrucksTracking.Domain.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Card")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Card");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Group");

                    b.ToTable("Transactions", "TuckTracking");
                });

            modelBuilder.Entity("Foruscorp.TrucksTracking.Domain.Trucks.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("RouteId");

                    b.Property<Guid>("TruckId")
                        .HasColumnType("uuid")
                        .HasColumnName("TruckId");

                    b.Property<Guid>("TruckTrackerId")
                        .HasColumnType("uuid")
                        .HasColumnName("TruckTrackerId");

                    b.HasKey("Id");

                    b.HasIndex("TruckId");

                    b.HasIndex("TruckTrackerId");

                    b.ToTable("Routes", "TuckTracking");
                });

            modelBuilder.Entity("Foruscorp.TrucksTracking.Domain.Trucks.TruckFuel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TruckFuelId");

                    b.Property<double>("NewFuelLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("PreviousFuelLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TruckId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TruckLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TruckTrackerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TruckLocationId");

                    b.HasIndex("TruckTrackerId");

                    b.ToTable("TruckFuelHistory", "TuckTracking");
                });

            modelBuilder.Entity("Foruscorp.TrucksTracking.Domain.Trucks.TruckLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TruckLocationId");

                    b.Property<Guid?>("CurrentTruckTrackerId")
                        .HasColumnType("uuid");

                    b.Property<string>("FormattedLocation")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TruckId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TruckTrackerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TruckTrackerId");

                    b.HasIndex("TruckId", "RecordedAt")
                        .IsDescending(false, true);

                    b.ToTable("TruckLocationHistory", "TuckTracking");
                });

            modelBuilder.Entity("Foruscorp.TrucksTracking.Domain.Trucks.TruckTracker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid?>("CurrentRouteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentTruckLocationId")
                        .HasColumnType("uuid");

                    b.Property<double>("FuelStatus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProviderTruckId")
                        .HasColumnType("text");

                    b.Property<int>("TruckEngineStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("TruckId")
                        .HasColumnType("uuid")
                        .HasColumnName("TruckId");

                    b.Property<int>("TruckStatus")
                        .HasColumnType("integer");

                    b.Property<int>("TruckTrackerStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRouteId")
                        .IsUnique();

                    b.HasIndex("CurrentTruckLocationId");

                    b.HasIndex("TruckId");

                    b.ToTable("TruckTrackers", "TuckTracking");
                });

            modelBuilder.Entity("Foruscorp.TrucksTracking.Domain.FuelStationPlans.NearFuelStationPlan", b =>
                {
                    b.HasOne("Foruscorp.TrucksTracking.Domain.Trucks.TruckLocation", "RecordedOnLocation")
                        .WithMany()
                        .HasForeignKey("RecordedOnLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RecordedOnLocation");
                });

            modelBuilder.Entity("Foruscorp.TrucksTracking.Domain.Transactions.Fill", b =>
                {
                    b.HasOne("Foruscorp.TrucksTracking.Domain.Transactions.Transaction", null)
                        .WithMany("Fills")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Foruscorp.TrucksTracking.Domain.Transactions.Item", b =>
                {
                    b.HasOne("Foruscorp.TrucksTracking.Domain.Transactions.Fill", null)
                        .WithMany("Items")
                        .HasForeignKey("FillId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Foruscorp.TrucksTracking.Domain.Trucks.Route", b =>
                {
                    b.HasOne("Foruscorp.TrucksTracking.Domain.Trucks.TruckTracker", null)
                        .WithMany("Routes")
                        .HasForeignKey("TruckTrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Foruscorp.TrucksTracking.Domain.Trucks.TruckFuel", b =>
                {
                    b.HasOne("Foruscorp.TrucksTracking.Domain.Trucks.TruckLocation", "TruckLocation")
                        .WithMany()
                        .HasForeignKey("TruckLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Foruscorp.TrucksTracking.Domain.Trucks.TruckTracker", null)
                        .WithMany("FuelHistory")
                        .HasForeignKey("TruckTrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TruckLocation");
                });

            modelBuilder.Entity("Foruscorp.TrucksTracking.Domain.Trucks.TruckLocation", b =>
                {
                    b.HasOne("Foruscorp.TrucksTracking.Domain.Trucks.TruckTracker", null)
                        .WithMany("TruckLocationHistory")
                        .HasForeignKey("TruckTrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Foruscorp.TrucksTracking.Domain.Trucks.GeoPoint", "Location", b1 =>
                        {
                            b1.Property<Guid>("TruckLocationId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("Longitude");

                            b1.HasKey("TruckLocationId");

                            b1.ToTable("TruckLocationHistory", "TuckTracking");

                            b1.WithOwner()
                                .HasForeignKey("TruckLocationId");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Foruscorp.TrucksTracking.Domain.Trucks.TruckTracker", b =>
                {
                    b.HasOne("Foruscorp.TrucksTracking.Domain.Trucks.Route", "CurrentRoute")
                        .WithOne()
                        .HasForeignKey("Foruscorp.TrucksTracking.Domain.Trucks.TruckTracker", "CurrentRouteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Foruscorp.TrucksTracking.Domain.Trucks.TruckLocation", "CurrentTruckLocation")
                        .WithMany()
                        .HasForeignKey("CurrentTruckLocationId");

                    b.Navigation("CurrentRoute");

                    b.Navigation("CurrentTruckLocation");
                });

            modelBuilder.Entity("Foruscorp.TrucksTracking.Domain.Transactions.Fill", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Foruscorp.TrucksTracking.Domain.Transactions.Transaction", b =>
                {
                    b.Navigation("Fills");
                });

            modelBuilder.Entity("Foruscorp.TrucksTracking.Domain.Trucks.TruckTracker", b =>
                {
                    b.Navigation("FuelHistory");

                    b.Navigation("Routes");

                    b.Navigation("TruckLocationHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
